/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ittapiros;

import javax.swing.JButton;

/**
 *
 * @author varad
 */
public class JatekFelulet extends javax.swing.JFrame {

    private int piros;

    /**
     * Creates new form JatekFelulet
     */
    public JatekFelulet() {
        kezd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEgy = new javax.swing.JButton();
        btnKetto = new javax.swing.JButton();
        btnHarom = new javax.swing.JButton();
        lbTalaltE = new javax.swing.JLabel();
        cbUjraoszt = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFajl = new javax.swing.JMenu();
        mnuUjJatek = new javax.swing.JMenuItem();
        mnuMentes = new javax.swing.JMenuItem();
        mnuBetoltes = new javax.swing.JMenuItem();
        mnuJatek = new javax.swing.JMenu();
        mnuHaromP = new javax.swing.JMenuItem();
        mnuNegyP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Itt a piros");

        jPanel1.setLayout(new java.awt.GridLayout());

        btnEgy.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEgy.setText("1");
        btnEgy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgyActionPerformed(evt);
            }
        });
        jPanel1.add(btnEgy);

        btnKetto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnKetto.setText("2");
        btnKetto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKettoActionPerformed(evt);
            }
        });
        jPanel1.add(btnKetto);

        btnHarom.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnHarom.setText("3");
        btnHarom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaromActionPerformed(evt);
            }
        });
        jPanel1.add(btnHarom);

        lbTalaltE.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbTalaltE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTalaltE.setText("Eltaláltad/Nem találtad el");

        cbUjraoszt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbUjraoszt.setText("Tippenként újraoszt");

        mnuFajl.setText("Fájl");

        mnuUjJatek.setText("Új játék");
        mnuUjJatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUjJatekActionPerformed(evt);
            }
        });
        mnuFajl.add(mnuUjJatek);

        mnuMentes.setText("Mentés");
        mnuFajl.add(mnuMentes);

        mnuBetoltes.setText("Betöltés");
        mnuFajl.add(mnuBetoltes);

        jMenuBar1.add(mnuFajl);

        mnuJatek.setText("Játék");

        mnuHaromP.setText("3 pohár");
        mnuJatek.add(mnuHaromP);

        mnuNegyP.setText("4 pohár");
        mnuJatek.add(mnuNegyP);

        jMenuBar1.add(mnuJatek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTalaltE, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbUjraoszt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTalaltE, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addGap(79, 79, 79)
                .addComponent(cbUjraoszt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgyActionPerformed
        if (cbUjraoszt.isSelected()) {
            golyotElhelyez();
        }
        TalaltE(btnEgy);

    }//GEN-LAST:event_btnEgyActionPerformed


    private void btnKettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKettoActionPerformed
        if (cbUjraoszt.isSelected()) {
            golyotElhelyez();
        }
        TalaltE(btnKetto);
    }//GEN-LAST:event_btnKettoActionPerformed

    private void btnHaromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaromActionPerformed
        if (cbUjraoszt.isSelected()) {
            golyotElhelyez();
        }
        TalaltE(btnHarom);
    }//GEN-LAST:event_btnHaromActionPerformed

    private void mnuUjJatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUjJatekActionPerformed
       lbTalaltE.setText("");
       golyotElhelyez();
       cbUjraoszt.setSelected(false);
       kezd();
       

    }//GEN-LAST:event_mnuUjJatekActionPerformed

    public void kezd() {
        initComponents();
        golyotElhelyez();

    }

    private void TalaltE(JButton gomb) {
        int szam = Integer.parseInt(gomb.getText());
        if (szam == piros) {
            lbTalaltE.setText("Eltaláltad!");
        } else {
            lbTalaltE.setText("Nem találtad el!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JatekFelulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JatekFelulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JatekFelulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JatekFelulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JatekFelulet().setVisible(true);
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEgy;
    private javax.swing.JButton btnHarom;
    private javax.swing.JButton btnKetto;
    private javax.swing.JCheckBox cbUjraoszt;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTalaltE;
    private javax.swing.JMenuItem mnuBetoltes;
    private javax.swing.JMenu mnuFajl;
    private javax.swing.JMenuItem mnuHaromP;
    private javax.swing.JMenu mnuJatek;
    private javax.swing.JMenuItem mnuMentes;
    private javax.swing.JMenuItem mnuNegyP;
    private javax.swing.JMenuItem mnuUjJatek;
    // End of variables declaration//GEN-END:variables

    private void golyotElhelyez() {
        piros = (int) (Math.random() * 3) + 1;
    }
}
